#!/bin/bash

# {{{ Colours
source "$HOME/.style/gruvbox"

# BG/FG
export style_bg0="$style_dark0"
export style_bg1="$style_dark1"
export style_bg2="$style_dark2"
export style_bg3="$style_dark3"
export style_bg4="$style_dark4"
export style_bg="$style_bg0"
export style_fg0="$style_light0"
export style_fg1="$style_light1"
export style_fg2="$style_light2"
export style_fg3="$style_light3"
export style_fg4="$style_light4"
export style_fg="$style_fg1"

# BG/FG - Bit
export style_bit_bg0="$style_bit_dark0"
export style_bit_bg1="$style_bit_dark1"
export style_bit_bg2="$style_bit_dark2"
export style_bit_bg3="$style_bit_dark3"
export style_bit_bg4="$style_bit_dark4"
export style_bit_bg="$style_bit_bg0"
export style_bit_fg0="$style_bit_light0"
export style_bit_fg1="$style_bit_light1"
export style_bit_fg2="$style_bit_light2"
export style_bit_fg3="$style_bit_light3"
export style_bit_fg4="$style_bit_light4"
export style_bit_fg="$style_bit_fg1"

# ANSI colours
export style_color0="$style_bg"
export style_color8="$style_grey"
export style_color1="$style_red"
export style_color9="$style_red_b"
export style_color2="$style_green"
export style_color10="$style_green_b"
export style_color3="$style_yellow"
export style_color11="$style_yellow_b"
export style_color4="$style_blue"
export style_color12="$style_blue_b"
export style_color5="$style_purple"
export style_color13="$style_purple_b"
export style_color6="$style_aqua"
export style_color14="$style_aqua_b"
export style_color7="$style_fg4"
export style_color15="$style_fg1"
# }}}

# {{{ WM
export style_window_gap=8
export style_border_width=2

export style_bar_height=24
export style_bar_radius=$(echo "$style_bar_height 2 / p" | dc)

export style_monitor_width="$(xrandr | grep -Po 'primary\s\K\d+(?=x)')"
export style_monitor_height="$(xrandr | grep -Po 'primary\s\d*x\K\d*')"
# }}}
