#! /bin/sh

sxhkd &
compton --config ~/.config/compton/compton.conf -b & 
$HOME/.config/polybar/run
#feh --bg-fill ~/.backs/nature/0cGG4pV.jpg
$HOME/.bin/backgrounds &
dunst &
#devmon --no-gui &
#mpd &

if [[ $(uname -n | grep -o 'lap$') == 'lap' ]]
then
  bspc monitor -d {1..22}
else
  bspc monitor -d {1..22}
fi

bspc config border_width         2
bspc config window_gap           8

bspc config initial_polarity second_child
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer false
bspc config focus_by_distance true

bspc config normal_border_color '#928374'
bspc config focused_border_color '#ebdbb2'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#4e4e4e'
bspc config focused_sticky_border_color '#83a598'
bspc config urgent_border_color '#fb4934'

$HOME/.config/bspwm/subscriptions.sh

# Rules
bspc rule -a Cheatsheet state=floating sticky=on focus=on rectangle=600x400+383+30

bspc config external_rules_command $HOME/.config/bspwm/external.sh
