#! /bin/bash

sxhkd &
compton --config ~/.config/compton/compton.conf -b & 
redshift -m randr -l 51.0486:'-114.0708' &
"$HOME/.config/polybar/run"
"$HOME/.bin/backgrounds" &
dunst &
mpd &

"$HOME/.config/bspwm/rules.sh"

"$HOME/.config/bspwm/subscriptions.sh"

# Rules
# bspc rule -a Cheatsheet state=floating sticky=on focus=on rectangle=600x400+383+30

bspc config external_rules_command "$HOME/.config/bspwm/external.sh"
