#!/bin/sh
# $Xorg: Xsetup_0,v 1.3 2000/08/17 19:54:17 cpqbld Exp $
#xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail

# Fix backspace problem in login box:
#sysmodmap=/etc/X11/xinit/.Xmodmap
#if [ -f $sysmodmap ]; then
#	/usr/bin/xmodmap $sysmodmap
#fi

# If the nifty KDE background loader is around, use it:
compton --config /home/lorx/.config/compton/compton.conf -b &
feh --bg-fill /home/lorx/.backs/0cGG4pV.jpg
#xprop > /etc/X11/xdm/prop.txt
#	/usr/bin/xsetroot -solid SteelBlue
