#!/bin/bash
killall polybar

(
export MONITOR=$(polybar -m | tail -1 | sed -e 's/:.*$//g')
export NETWORK=$(ip addr | pcre2grep -M 'UP.*\n.*\n.*/24' | grep -oP '^\d*: \K[^:]*')
export TOP_RIGHT_WIDTH=400
export TOP_RIGHT_OFFSET=$(echo $(polybar -m | tail -1 | grep -oP '\d*(?=x)') 0 - $TOP_RIGHT_WIDTH - p | dc)
export BOTTOM_RIGHT_WIDTH=500
export BOTTOM_RIGHT_OFFSET=$(echo $(polybar -m | tail -1 | grep -oP '\d*(?=x)') 0 - $BOTTOM_RIGHT_WIDTH - p | dc)

polybar wm -r & 
polybar topright -r &
polybar bottomright -r &
)
